AWSTemplateFormatVersion: 2010-09-09

Description: Provisioning of 2 EC2 Instances within a Custom Network via Cloudformation

  InternetGateWay:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: ProjectIGW 